settings:
  # Как часто проверять ранги игроков? В минутах
  timer: 1
  # Сообщение при получение ранга
  getting_message: "&9&oСистема &f&oрангов&8> &fВы повысили свой ранг до &a%rank&f!"
  # Сообщение при получении ранга
  broadcast_message: "&9&oСистема &f&oрангов&8> &a%player&f только что получил ранг &a%rank&f!"
  # Сообщение при недостатке наигранного времени для получения ранга
  no_time: "&9&oСистема &f&oрангов&8> &cДля получения ранга &e%rank&c вам требуется наиграть ещё &e%time часов&c!"
  # Сообщение, если введеный в команде ранг не существует
  no_rank: "&9&oСистема &f&oрангов&8> &cРанга &e%rank&c не существует на этом сервере!"
  # Список команд
  help_messages:
    - '&a/rank info &7- краткая информация о рангах'
    - '&a/rank info ранг &7- информация о конкретном ранге'
    - '&a/rank ранг &7- повышение ранга'
  # Сообщения /rank info
  info_messages:
    - '&e&m                                                                     &9'
    - '&eРанги&f позволяют получить улучшения &aприватов&f, &aточек дома&f.'
    - 'Также &eранги&f дают некоторые небольшие возможности, вроде использования &a/hat&f.'
    - 'Получение &eрангов&f производится путем &eобычной игры&f на сервере.'
    - 'Вам &aне требуется&f платить за это - просто &aоставайтесь с нами&f! ;)'
    - '&e&m                                                                     &9'
ranks:
  # xrank.rank.newbie - право на получение ранга
  # xrank.rank.newbie.got - право, которое означает, что ранг уже получен
  newbie:
    # Количество минут до получения ранга
    minutes: 1480
    # true С момента входа игрок
    # false Сколько игрок наиграл
    from_join: true
    # "Красивое" название ранга. Можно на русском
    name: Newbie
    # Описание того, что позволяет ранг
    description:
      - '&aВы больше не гость!'
    # true Игрок получит ранг автоматически при получении ранга
    # false Игрока попросят написать команду
    auto: true
    # true Показывает объявление всем в чате
    # false Только игрок будет видеть сообщение о повышении
    broadcast: false
    # Команды, которые будут введены с консоли, при повышении ранга игрока. %player заменится на ник игрока
    commands:
      - lp user %player promote player
      - eco give %player 50
  # Право xrank.rank.usual
  usual:
    minutes: 2960
    from_join: false
    name: Usual
    description:
      - '&6Вы больше не будете новичком! Просто введите /rank usual'
    auto: false
    broadcast: true
    commands:
      - lp user %player promote player
      - eco give %player 1000