name: xRank
version: '${project.version}'
main: me.imdanix.rank.RankPlugin
api-version: '1.13'
authors: [imDaniX]
description: '${project.version}'
commands:
  xrank:
    aliases: [rank,ranks]
    permission: xrank.command