name: xRank
version: ${project.version}
main: me.imdanix.rank.RankPlugin
api-version: 1.13
load: STARTUP
authors: [imDaniX]
description: Simple rank plugin
commands:
  xrank:
    aliases: [rank,ranks]
    permission: xrank.command